### ISSUE TITLE
message.DeviceName should accept comma-separated values

### ISSUE THREAD

**Issue by entonio** [gregdel/pushover#17]
Hi. According to https://pushover.net/api, 

> device - your user's device name to send the message directly to that device, rather than all of the user's devices (multiple devices may be separated by a comma)

but the current validation does not accept that:

> deviceNameRegexp = regexp.MustCompile(`^[A-Za-z0-9_-]{1,25}$`)

(In general, I find it's not a good idea to perform extensive second-tier validations - if there's a problem with the device name, then Pushover can validate that by itself, and the cost of doing it is less than the risk of not letting a value wrongly classified as inavlid reach the actual engine that uses it. I'm not sure a proper device name can't have spaces or apostrophes, for example, nor am I sure about the 25 char limit. Even if those are the actual constrains by Pushover, they can change on their side and then require changes on this side lest one can't target valid devices. The validation is imo in vain for the use case of a wrapper lib - it should be the concern of the lib user to provide valid names.)

But in this specific case I don't mind the validation, it's just that it's precluding a multi-device message.

**Comment by gregdel** [comment]
Hello @entonio ,

You're right, this feature was not implemented ! He're a PR, what do you think: https://github.com/gregdel/pushover/pull/18 ?

I agree with you, the validation could be avoided in the lib but it would break the current behavior. The API's documentation explicitly gives the regexp for matching valid user names, devices names, tokens.. that's why I wrote validation on client side.
I would also expect the API endpoint to change if they were to change the API's behaviour (so this lib would still work after the update).

I'm not against making the validation optional, avoiding work on the client side, if this is what the users of this lib wants :)
(But i don't think this is a lot of work)

Thanks for contribution !

**Comment by entonio** [comment]
Looks good to me! Thanks for the quick response.
I don't think the processing time should be a concern. My issue is only with the potential to make valid input unable to reach the engine. As you mention, a bool to make validation optional could solve that problem. But at least with this correction there seems to be no problem any more (unless they change what the endpoint accepts!).

**Comment by gregdel** [comment]
Merged ! Thank you for your contribution :)
